import Header from '@/component/Header';
import { AuthProvider } from '@/state/AuthContext';
import clsx from 'clsx';
import { Noto_Sans_JP } from 'next/font/google';
import React from 'react';

import '../styles/globals.css';
import { SnackbarProvider } from '@/component/SnackBar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
});

/**
 * レイアウト
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja" className={clsx(notoSansJP.variable, 'font-sans')}>
      <body>
        <SnackbarProvider>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </SnackbarProvider>
      </body>
    </html>
  );
}
