name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PR Agent action
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PR_AGENT_MODEL_PROVIDER: "azure"
          PR_AGENT_LANGUAGE: "Japanese"
          AZURE_OPENAI_ENDPOINT: "https://sample-jpn.openai.azure.com"
          AZURE_OPENAI_DEPLOYMENT_NAME: "gpt-4o"
          AZURE_OPENAI_API_VERSION: "2023-03-15-preview"
