name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

env:
  EXTRA_SETTINGS: |
    必ず日本語で回答してください。
    文章が日本語で回答されているかを確認し、
    英語になっている場合は日本語にしてください。

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PR Agent action
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI_API_TYPE: "azure"
          OPENAI_API_BASE: "https://sample-jpn.openai.azure.com"
          OPENAI_DEPLOYMENT_ID: "gpt-4o"
          OPENAI_API_VERSION: "2023-03-15-preview"
          PR_AGENT_MODEL_PROVIDER: "azure"
          PR_AGENT_LANGUAGE: "Japanese"
          EXTRA_SETTINGS: ${{ env.EXTRA_SETTINGS }}
