name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    if: |
      github.event.sender.type != 'Bot' && (
        github.event_name == 'pull_request' ||
        github.event_name == 'issue_comment'
      )

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PR Agent action
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          PR_AGENT_MODEL_PROVIDER: "azure"
          PR_AGENT_AZURE_ENGINE: "gpt-4o"
          PR_AGENT_AZURE_API_BASE: "https://sample-jpn.openai.azure.com"
          PR_AGENT_AZURE_API_VERSION: "2023-03-15-preview"
          PR_AGENT_LANGUAGE: "Japanese"
          PR_AGENT_SYSTEM_MESSAGE: |
            あなたは経験豊富なソフトウェアエンジニアとして、
            PRの内容を分析し、詳細なレビューを提供します。
            必ず日本語で回答を行い、
            セキュリティ、パフォーマンス、保守性の観点から分析してください。
          PR_AGENT_TIMEOUT: "600"
          PR_AGENT_AUTO_DESCRIBE: "false"
          PR_AGENT_AUTO_REVIEW: "true" # 変更：falseからtrueに
          PR_AGENT_AUTO_IMPROVE: "true"
          PR_AGENT_INCREMENTAL_MODE: "true" # 追加：増分モードを有効化
